USE ROLE CRI_DEV_LOADER_ROLE;
USE WAREHOUSE CRI_DEV_WH;
USE DATABASE CRI_DEV;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS STATCAN_CONTROL_CSV
    TYPE = CSV
    COMPRESSION = AUTO
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL')
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    ENCODING = 'UTF8';

CREATE FILE FORMAT IF NOT EXISTS STATCAN_DATA_CSV
    TYPE = CSV
    COMPRESSION = AUTO
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    ENCODING = 'UTF8';

CREATE TABLE IF NOT EXISTS BATCH_CONTROL (
    TABLE_ID VARCHAR NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    SUBJECT VARCHAR NOT NULL,
    SOURCE_URL VARCHAR NOT NULL,
    SOURCE_LAST_MODIFIED_UTC VARCHAR,
    INGESTED_AT_UTC VARCHAR NOT NULL,
    SOURCE_ARCHIVE_SHA256 VARCHAR NOT NULL,
    DATA_CSV_SHA256 VARCHAR NOT NULL,
    SOURCE_RECORD_COUNT VARCHAR NOT NULL,
    DATA_PATH VARCHAR NOT NULL,
    MANIFEST_PATH VARCHAR NOT NULL,
    SOURCE_FILE VARCHAR NOT NULL,
    SOURCE_ROW_NUMBER NUMBER NOT NULL,
    SOURCE_LOADED_AT TIMESTAMP_LTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS SOURCE_ROW (
    TABLE_ID VARCHAR NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    C01 VARCHAR,
    C02 VARCHAR,
    C03 VARCHAR,
    C04 VARCHAR,
    C05 VARCHAR,
    C06 VARCHAR,
    C07 VARCHAR,
    C08 VARCHAR,
    C09 VARCHAR,
    C10 VARCHAR,
    C11 VARCHAR,
    C12 VARCHAR,
    C13 VARCHAR,
    C14 VARCHAR,
    C15 VARCHAR,
    C16 VARCHAR,
    C17 VARCHAR,
    SOURCE_FILE VARCHAR NOT NULL,
    SOURCE_ROW_NUMBER NUMBER NOT NULL,
    SOURCE_LOADED_AT TIMESTAMP_LTZ NOT NULL
);

CREATE PIPE IF NOT EXISTS BATCH_CONTROL_PIPE
    AUTO_INGEST = TRUE
    INTEGRATION = 'CRI_DEV_AZURE_QUEUE_INT'
    COMMENT = 'Loads only immutable READY control rows after complete batch publication.'
AS
COPY INTO BATCH_CONTROL (
    TABLE_ID,
    BATCH_ID,
    SUBJECT,
    SOURCE_URL,
    SOURCE_LAST_MODIFIED_UTC,
    INGESTED_AT_UTC,
    SOURCE_ARCHIVE_SHA256,
    DATA_CSV_SHA256,
    SOURCE_RECORD_COUNT,
    DATA_PATH,
    MANIFEST_PATH,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER,
    SOURCE_LOADED_AT
)
FROM (
    SELECT
        T.$1,
        T.$2,
        T.$3,
        T.$4,
        T.$5,
        T.$6,
        T.$7,
        T.$8,
        T.$9,
        T.$10,
        T.$11,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        METADATA$START_SCAN_TIME
    FROM @STATCAN_LANDING_STAGE T
)
FILE_FORMAT = (FORMAT_NAME = STATCAN_CONTROL_CSV)
PATTERN = '.*/_READY[.]csv';
