USE ROLE CRI_DEV_TRANSFORMER_ROLE;
USE WAREHOUSE CRI_DEV_WH;
USE DATABASE CRI_DEV;

CREATE STREAM IF NOT EXISTS CORE.BATCH_CONTROL_STREAM
    ON TABLE RAW.BATCH_CONTROL
    APPEND_ONLY = TRUE;

CREATE TABLE IF NOT EXISTS OPS.PIPELINE_RUN (
    RUN_ID VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_LTZ NOT NULL,
    FINISHED_AT TIMESTAMP_LTZ,
    STATUS VARCHAR NOT NULL,
    BATCHES_PUBLISHED NUMBER DEFAULT 0,
    BATCHES_QUARANTINED NUMBER DEFAULT 0,
    ERROR_MESSAGE VARCHAR
);

CREATE TABLE IF NOT EXISTS OPS.LOAD_BATCH (
    BATCH_ID VARCHAR NOT NULL,
    TABLE_ID VARCHAR NOT NULL,
    SUBJECT VARCHAR NOT NULL,
    SOURCE_URL VARCHAR NOT NULL,
    SOURCE_RELEASE_TS TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL,
    SOURCE_ARCHIVE_SHA256 VARCHAR NOT NULL,
    DATA_CSV_SHA256 VARCHAR NOT NULL,
    EXPECTED_RECORD_COUNT NUMBER NOT NULL,
    ACTUAL_RECORD_COUNT NUMBER,
    VALID_RECORD_COUNT NUMBER,
    DATA_PATH VARCHAR NOT NULL,
    MANIFEST_PATH VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    STATUS_REASON VARCHAR,
    FIRST_SEEN_AT TIMESTAMP_LTZ NOT NULL,
    PROCESSED_AT TIMESTAMP_LTZ,
    RUN_ID VARCHAR
);

CREATE TABLE IF NOT EXISTS OPS.QUALITY_RESULT (
    RUN_ID VARCHAR NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    CHECK_NAME VARCHAR NOT NULL,
    SEVERITY VARCHAR NOT NULL,
    PASSED BOOLEAN NOT NULL,
    ACTUAL_VALUE VARCHAR,
    EXPECTED_VALUE VARCHAR,
    CHECKED_AT TIMESTAMP_LTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS OPS.RECORD_OUTCOME (
    RUN_ID VARCHAR NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    SOURCE_RECORDS NUMBER NOT NULL,
    VALID_RECORDS NUMBER NOT NULL,
    PUBLISHED_RECORDS NUMBER NOT NULL,
    FILTERED_RECORDS NUMBER NOT NULL,
    RECORDED_AT TIMESTAMP_LTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS OPS.QUARANTINE_BATCH (
    RUN_ID VARCHAR NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    TABLE_ID VARCHAR,
    REASON VARCHAR NOT NULL,
    CONTROL_PAYLOAD VARIANT,
    QUARANTINED_AT TIMESTAMP_LTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.FACT_POPULATION_HISTORY (
    CMA_DGUID VARCHAR NOT NULL,
    CMA_NAME VARCHAR NOT NULL,
    PROVINCE_NAME VARCHAR NOT NULL,
    REF_YEAR NUMBER(4, 0) NOT NULL,
    POPULATION NUMBER(18, 0) NOT NULL,
    UNIT VARCHAR NOT NULL,
    RECORD_HASH VARCHAR NOT NULL,
    SOURCE_RELEASE_TS TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    VALID_FROM_TS TIMESTAMP_TZ NOT NULL,
    VALID_TO_TS TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.FACT_LABOUR_HISTORY (
    CMA_DGUID VARCHAR NOT NULL,
    CMA_NAME VARCHAR NOT NULL,
    PROVINCE_NAME VARCHAR NOT NULL,
    REF_YEAR NUMBER(4, 0) NOT NULL,
    METRIC_NAME VARCHAR NOT NULL,
    METRIC_VALUE NUMBER(18, 3) NOT NULL,
    UNIT VARCHAR NOT NULL,
    RECORD_HASH VARCHAR NOT NULL,
    SOURCE_RELEASE_TS TIMESTAMP_TZ NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    VALID_FROM_TS TIMESTAMP_TZ NOT NULL,
    VALID_TO_TS TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN NOT NULL
);
