USE ROLE CRI_DEV_TRANSFORMER_ROLE;
USE WAREHOUSE CRI_DEV_WH;
USE DATABASE CRI_DEV;
USE SCHEMA CORE;

CREATE TASK IF NOT EXISTS PROCESS_BATCH_TASK
    WAREHOUSE = CRI_DEV_WH
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
    USER_TASK_TIMEOUT_MS = 1800000
    WHEN SYSTEM$STREAM_HAS_DATA('CRI_DEV.CORE.BATCH_CONTROL_STREAM')
AS
    CALL CRI_DEV.CORE.PROCESS_NEW_BATCHES();

ALTER TASK PROCESS_BATCH_TASK RESUME;
