USE ROLE CRI_DEV_TRANSFORMER_ROLE;
USE WAREHOUSE CRI_DEV_WH;
USE DATABASE CRI_DEV;

CREATE OR REPLACE VIEW OPS.VW_BATCH_HEALTH AS
SELECT
    BATCH_ID,
    TABLE_ID,
    SUBJECT,
    SOURCE_RELEASE_TS,
    EXPECTED_RECORD_COUNT,
    ACTUAL_RECORD_COUNT,
    VALID_RECORD_COUNT,
    STATUS,
    STATUS_REASON,
    FIRST_SEEN_AT,
    PROCESSED_AT,
    DATEDIFF('second', FIRST_SEEN_AT, PROCESSED_AT) AS PROCESSING_SECONDS,
    RUN_ID
FROM OPS.LOAD_BATCH;

CREATE OR REPLACE VIEW OPS.VW_QUALITY_SUMMARY AS
SELECT
    BATCH_ID,
    COUNT(*) AS CHECK_COUNT,
    COUNT_IF(PASSED) AS PASSED_CHECK_COUNT,
    COUNT_IF(NOT PASSED AND SEVERITY = 'ERROR') AS FAILED_ERROR_COUNT,
    MAX(CHECKED_AT) AS LAST_CHECKED_AT
FROM OPS.QUALITY_RESULT
GROUP BY BATCH_ID;

CREATE OR REPLACE VIEW OPS.VW_RECONCILIATION AS
SELECT
    BATCH_ID,
    SOURCE_RECORDS,
    VALID_RECORDS,
    PUBLISHED_RECORDS,
    FILTERED_RECORDS,
    SOURCE_RECORDS = VALID_RECORDS + FILTERED_RECORDS AS RECONCILES,
    RECORDED_AT
FROM OPS.RECORD_OUTCOME;
