USE ROLE CRI_DEV_TRANSFORMER_ROLE;
USE WAREHOUSE CRI_DEV_WH;
USE DATABASE CRI_DEV;

CREATE OR REPLACE VIEW CORE.VW_POPULATION_CURRENT AS
SELECT * EXCLUDE (RECORD_HASH, VALID_FROM_TS, VALID_TO_TS, IS_CURRENT)
FROM CORE.FACT_POPULATION_HISTORY
WHERE IS_CURRENT;

CREATE OR REPLACE VIEW CORE.VW_LABOUR_CURRENT AS
SELECT * EXCLUDE (RECORD_HASH, VALID_FROM_TS, VALID_TO_TS, IS_CURRENT)
FROM CORE.FACT_LABOUR_HISTORY
WHERE IS_CURRENT;

CREATE OR REPLACE VIEW CORE.DIM_CMA AS
SELECT
    CMA_DGUID,
    RIGHT(CMA_DGUID, 3) AS CMA_CODE,
    MAX(CMA_NAME) AS CMA_NAME,
    MAX(PROVINCE_NAME) AS PROVINCE_NAME
FROM (
    SELECT CMA_DGUID, CMA_NAME, PROVINCE_NAME FROM CORE.VW_POPULATION_CURRENT
    UNION ALL
    SELECT CMA_DGUID, CMA_NAME, PROVINCE_NAME FROM CORE.VW_LABOUR_CURRENT
)
GROUP BY CMA_DGUID;

CREATE OR REPLACE VIEW MART.CMA_YEAR_LABOUR_MARKET AS
WITH LABOUR AS (
    SELECT
        CMA_DGUID,
        REF_YEAR,
        MAX(IFF(METRIC_NAME = 'Population', METRIC_VALUE, NULL)) AS WORKING_AGE_POPULATION_THOUSANDS,
        MAX(IFF(METRIC_NAME = 'Labour force', METRIC_VALUE, NULL)) AS LABOUR_FORCE_THOUSANDS,
        MAX(IFF(METRIC_NAME = 'Employment', METRIC_VALUE, NULL)) AS EMPLOYMENT_THOUSANDS,
        MAX(IFF(METRIC_NAME = 'Unemployment', METRIC_VALUE, NULL)) AS UNEMPLOYMENT_THOUSANDS,
        MAX(IFF(METRIC_NAME = 'Unemployment rate', METRIC_VALUE, NULL)) AS UNEMPLOYMENT_RATE_PCT,
        MAX(IFF(METRIC_NAME = 'Participation rate', METRIC_VALUE, NULL)) AS PARTICIPATION_RATE_PCT,
        MAX(IFF(METRIC_NAME = 'Employment rate', METRIC_VALUE, NULL)) AS EMPLOYMENT_RATE_PCT,
        MAX(SOURCE_RELEASE_TS) AS LABOUR_SOURCE_RELEASE_TS
    FROM CORE.VW_LABOUR_CURRENT
    GROUP BY CMA_DGUID, REF_YEAR
), POPULATION_WITH_LAG AS (
    SELECT
        CMA_DGUID,
        REF_YEAR,
        POPULATION,
        SOURCE_RELEASE_TS AS POPULATION_SOURCE_RELEASE_TS,
        LAG(POPULATION) OVER (
            PARTITION BY CMA_DGUID
            ORDER BY REF_YEAR
        ) AS PRIOR_YEAR_POPULATION
    FROM CORE.VW_POPULATION_CURRENT
)
SELECT
    CMA.CMA_DGUID,
    CMA.CMA_CODE,
    CMA.CMA_NAME,
    CMA.PROVINCE_NAME,
    POP.REF_YEAR,
    POP.POPULATION,
    ROUND(
        100 * (POP.POPULATION - POP.PRIOR_YEAR_POPULATION)
        / NULLIF(POP.PRIOR_YEAR_POPULATION, 0),
        2
    ) AS POPULATION_YOY_PCT,
    LABOUR.WORKING_AGE_POPULATION_THOUSANDS,
    LABOUR.LABOUR_FORCE_THOUSANDS,
    LABOUR.EMPLOYMENT_THOUSANDS,
    LABOUR.UNEMPLOYMENT_THOUSANDS,
    LABOUR.UNEMPLOYMENT_RATE_PCT,
    LABOUR.PARTICIPATION_RATE_PCT,
    LABOUR.EMPLOYMENT_RATE_PCT,
    POP.POPULATION_SOURCE_RELEASE_TS,
    LABOUR.LABOUR_SOURCE_RELEASE_TS
FROM POPULATION_WITH_LAG AS POP
INNER JOIN LABOUR
    ON POP.CMA_DGUID = LABOUR.CMA_DGUID
    AND POP.REF_YEAR = LABOUR.REF_YEAR
INNER JOIN CORE.DIM_CMA AS CMA
    ON POP.CMA_DGUID = CMA.CMA_DGUID;
