USE ROLE CRI_DEV_TRANSFORMER_ROLE;
USE WAREHOUSE CRI_DEV_WH;
USE DATABASE CRI_DEV;

CREATE OR REPLACE VIEW MART.CMA_REGIONAL_OUTLOOK AS
WITH LATEST_YEAR AS (
    SELECT MAX(REF_YEAR) AS REF_YEAR
    FROM MART.CMA_YEAR_LABOUR_MARKET
), LATEST AS (
    SELECT MART.*
    FROM MART.CMA_YEAR_LABOUR_MARKET AS MART
    INNER JOIN LATEST_YEAR
        ON MART.REF_YEAR = LATEST_YEAR.REF_YEAR
), PRE_PANDEMIC_BASELINE AS (
    SELECT
        CMA_DGUID,
        POPULATION AS POPULATION_2019,
        UNEMPLOYMENT_RATE_PCT AS UNEMPLOYMENT_RATE_2019_PCT,
        PARTICIPATION_RATE_PCT AS PARTICIPATION_RATE_2019_PCT,
        EMPLOYMENT_RATE_PCT AS EMPLOYMENT_RATE_2019_PCT
    FROM MART.CMA_YEAR_LABOUR_MARKET
    WHERE REF_YEAR = 2019
), COMPARISON AS (
    SELECT
        LATEST.CMA_DGUID,
        LATEST.CMA_CODE,
        RTRIM(LATEST.CMA_NAME) AS CMA_NAME,
        LATEST.PROVINCE_NAME,
        LATEST.REF_YEAR,
        LATEST.POPULATION,
        LATEST.POPULATION - BASELINE.POPULATION_2019
            AS POPULATION_CHANGE_SINCE_2019,
        LATEST.POPULATION_YOY_PCT,
        LATEST.UNEMPLOYMENT_RATE_PCT,
        LATEST.PARTICIPATION_RATE_PCT,
        LATEST.EMPLOYMENT_RATE_PCT,
        ROUND(
            100 * (LATEST.POPULATION - BASELINE.POPULATION_2019)
            / NULLIF(BASELINE.POPULATION_2019, 0),
            2
        ) AS POPULATION_CHANGE_SINCE_2019_PCT,
        ROUND(
            LATEST.UNEMPLOYMENT_RATE_PCT
            - BASELINE.UNEMPLOYMENT_RATE_2019_PCT,
            1
        ) AS UNEMPLOYMENT_RATE_CHANGE_SINCE_2019_PP,
        ROUND(
            LATEST.PARTICIPATION_RATE_PCT
            - BASELINE.PARTICIPATION_RATE_2019_PCT,
            1
        ) AS PARTICIPATION_RATE_CHANGE_SINCE_2019_PP,
        ROUND(
            LATEST.EMPLOYMENT_RATE_PCT
            - BASELINE.EMPLOYMENT_RATE_2019_PCT,
            1
        ) AS EMPLOYMENT_RATE_CHANGE_SINCE_2019_PP
    FROM LATEST
    INNER JOIN PRE_PANDEMIC_BASELINE AS BASELINE
        ON LATEST.CMA_DGUID = BASELINE.CMA_DGUID
), BENCHMARKED AS (
    SELECT
        COMPARISON.*,
        MEDIAN(POPULATION_CHANGE_SINCE_2019_PCT) OVER ()
            AS MEDIAN_POPULATION_CHANGE_PCT,
        MEDIAN(UNEMPLOYMENT_RATE_PCT) OVER ()
            AS MEDIAN_UNEMPLOYMENT_RATE_PCT
    FROM COMPARISON
)
SELECT
    BENCHMARKED.*,
    CASE
        WHEN POPULATION_CHANGE_SINCE_2019_PCT
            >= MEDIAN_POPULATION_CHANGE_PCT
            AND UNEMPLOYMENT_RATE_PCT <= MEDIAN_UNEMPLOYMENT_RATE_PCT
            THEN 'HIGHER_GROWTH_LOWER_UNEMPLOYMENT'
        WHEN POPULATION_CHANGE_SINCE_2019_PCT
            >= MEDIAN_POPULATION_CHANGE_PCT
            AND UNEMPLOYMENT_RATE_PCT > MEDIAN_UNEMPLOYMENT_RATE_PCT
            THEN 'HIGHER_GROWTH_HIGHER_UNEMPLOYMENT'
        WHEN POPULATION_CHANGE_SINCE_2019_PCT
            < MEDIAN_POPULATION_CHANGE_PCT
            AND UNEMPLOYMENT_RATE_PCT <= MEDIAN_UNEMPLOYMENT_RATE_PCT
            THEN 'LOWER_GROWTH_LOWER_UNEMPLOYMENT'
        ELSE 'LOWER_GROWTH_HIGHER_UNEMPLOYMENT'
    END AS REGIONAL_QUADRANT
FROM BENCHMARKED;
