USE ROLE CRI_DEV_MONITOR_ROLE;
USE WAREHOUSE CRI_DEV_WH;
USE DATABASE CRI_DEV;

SELECT * FROM OPS.VW_BATCH_HEALTH ORDER BY FIRST_SEEN_AT DESC;
SELECT * FROM OPS.VW_QUALITY_SUMMARY ORDER BY LAST_CHECKED_AT DESC;
SELECT * FROM OPS.VW_RECONCILIATION ORDER BY RECORDED_AT DESC;

USE ROLE CRI_DEV_ANALYST_ROLE;

SELECT
    COUNT(*) AS MART_ROWS,
    COUNT(DISTINCT CMA_DGUID) AS CMA_COUNT,
    MIN(REF_YEAR) AS MIN_YEAR,
    MAX(REF_YEAR) AS MAX_YEAR
FROM MART.CMA_YEAR_LABOUR_MARKET;

SELECT
    CMA_NAME,
    PROVINCE_NAME,
    REF_YEAR,
    POPULATION,
    POPULATION_YOY_PCT,
    UNEMPLOYMENT_RATE_PCT,
    PARTICIPATION_RATE_PCT,
    EMPLOYMENT_RATE_PCT
FROM MART.CMA_YEAR_LABOUR_MARKET
QUALIFY REF_YEAR = MAX(REF_YEAR) OVER ()
ORDER BY POPULATION DESC
LIMIT 15;
