USE ROLE CRI_DEV_ANALYST_ROLE;
USE WAREHOUSE CRI_DEV_WH;

-- Dashboard KPI source: one row describing the current analytical snapshot.
SELECT
    MAX(REF_YEAR) AS LATEST_YEAR,
    COUNT(*) AS CMA_COUNT,
    SUM(POPULATION) AS COVERED_POPULATION,
    ROUND(MEDIAN(POPULATION_CHANGE_SINCE_2019_PCT), 2)
        AS MEDIAN_POPULATION_CHANGE_SINCE_2019_PCT,
    ROUND(MEDIAN(UNEMPLOYMENT_RATE_PCT), 1)
        AS MEDIAN_UNEMPLOYMENT_RATE_PCT,
    ROUND(
        CORR(
            POPULATION_CHANGE_SINCE_2019_PCT,
            UNEMPLOYMENT_RATE_PCT
        ),
        3
    ) AS GROWTH_UNEMPLOYMENT_CORRELATION
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK;

-- Dashboard scorecard sources: each query produces one display value.
SELECT MAX(REF_YEAR) AS LATEST_DATA_YEAR
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK;

SELECT COUNT(*) AS CMAS_COVERED
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK;

SELECT SUM(POPULATION) AS POPULATION_COVERED
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK;

SELECT ROUND(MEDIAN(POPULATION_CHANGE_SINCE_2019_PCT), 2)
    AS MEDIAN_POPULATION_GROWTH_PCT
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK;

SELECT ROUND(MEDIAN(UNEMPLOYMENT_RATE_PCT), 1)
    AS MEDIAN_UNEMPLOYMENT_RATE_PCT
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK;

-- Dashboard scatter source: compare growth and unemployment by CMA.
SELECT
    CMA_NAME,
    PROVINCE_NAME,
    POPULATION,
    POPULATION_CHANGE_SINCE_2019_PCT,
    UNEMPLOYMENT_RATE_PCT,
    EMPLOYMENT_RATE_CHANGE_SINCE_2019_PP,
    REGIONAL_QUADRANT
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK
ORDER BY POPULATION_CHANGE_SINCE_2019_PCT DESC;

-- Dashboard bar source: the fastest-growing CMAs since 2019.
SELECT
    CMA_NAME,
    POPULATION_CHANGE_SINCE_2019_PCT,
    UNEMPLOYMENT_RATE_PCT,
    EMPLOYMENT_RATE_CHANGE_SINCE_2019_PP,
    REGIONAL_QUADRANT
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK
QUALIFY ROW_NUMBER() OVER (
    ORDER BY POPULATION_CHANGE_SINCE_2019_PCT DESC
) <= 10
ORDER BY POPULATION_CHANGE_SINCE_2019_PCT DESC;

-- Dashboard risk table: CMAs with the largest employment-rate declines.
SELECT
    CMA_NAME,
    POPULATION_CHANGE_SINCE_2019_PCT,
    UNEMPLOYMENT_RATE_PCT,
    PARTICIPATION_RATE_CHANGE_SINCE_2019_PP,
    EMPLOYMENT_RATE_CHANGE_SINCE_2019_PP,
    REGIONAL_QUADRANT
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK
QUALIFY ROW_NUMBER() OVER (
    ORDER BY EMPLOYMENT_RATE_CHANGE_SINCE_2019_PP
) <= 10
ORDER BY EMPLOYMENT_RATE_CHANGE_SINCE_2019_PP;

-- Dashboard trend source: population growth indexed to 2019 for six large CMAs.
WITH LATEST_YEAR AS (
    SELECT MAX(REF_YEAR) AS REF_YEAR
    FROM CRI_DEV.MART.CMA_YEAR_LABOUR_MARKET
), LARGEST_CMAS AS (
    SELECT CMA_DGUID
    FROM CRI_DEV.MART.CMA_YEAR_LABOUR_MARKET
    WHERE REF_YEAR = (SELECT REF_YEAR FROM LATEST_YEAR)
    QUALIFY ROW_NUMBER() OVER (ORDER BY POPULATION DESC) <= 6
), BASELINE AS (
    SELECT
        CMA_DGUID,
        POPULATION AS POPULATION_2019
    FROM CRI_DEV.MART.CMA_YEAR_LABOUR_MARKET
    WHERE REF_YEAR = 2019
)
SELECT
    MART.REF_YEAR,
    RTRIM(MART.CMA_NAME) AS CMA_NAME,
    ROUND(100 * MART.POPULATION / NULLIF(BASELINE.POPULATION_2019, 0), 1)
        AS POPULATION_INDEX_2019_EQ_100
FROM CRI_DEV.MART.CMA_YEAR_LABOUR_MARKET AS MART
INNER JOIN LARGEST_CMAS
    ON MART.CMA_DGUID = LARGEST_CMAS.CMA_DGUID
INNER JOIN BASELINE
    ON MART.CMA_DGUID = BASELINE.CMA_DGUID
WHERE MART.REF_YEAR >= 2019
ORDER BY MART.REF_YEAR, CMA_NAME;
