USE ROLE CRI_DEV_ANALYST_ROLE;
USE WAREHOUSE CRI_DEV_WH;

-- Export as regional_outlook_2025.csv (41 rows).
SELECT
    CMA_DGUID,
    CMA_CODE,
    CMA_NAME,
    PROVINCE_NAME,
    REF_YEAR,
    POPULATION,
    POPULATION_CHANGE_SINCE_2019,
    POPULATION_CHANGE_SINCE_2019_PCT,
    POPULATION_YOY_PCT,
    UNEMPLOYMENT_RATE_PCT,
    UNEMPLOYMENT_RATE_CHANGE_SINCE_2019_PP,
    PARTICIPATION_RATE_PCT,
    PARTICIPATION_RATE_CHANGE_SINCE_2019_PP,
    EMPLOYMENT_RATE_PCT,
    EMPLOYMENT_RATE_CHANGE_SINCE_2019_PP,
    MEDIAN_POPULATION_CHANGE_PCT,
    MEDIAN_UNEMPLOYMENT_RATE_PCT,
    REGIONAL_QUADRANT
FROM CRI_DEV.MART.CMA_REGIONAL_OUTLOOK
ORDER BY POPULATION_CHANGE_SINCE_2019_PCT DESC;

-- Export as cma_year_trends_2011_2025.csv (615 rows).
WITH LATEST_YEAR AS (
    SELECT MAX(REF_YEAR) AS REF_YEAR
    FROM CRI_DEV.MART.CMA_YEAR_LABOUR_MARKET
), BASELINE AS (
    SELECT
        CMA_DGUID,
        POPULATION AS POPULATION_2019,
        UNEMPLOYMENT_RATE_PCT AS UNEMPLOYMENT_RATE_2019_PCT,
        PARTICIPATION_RATE_PCT AS PARTICIPATION_RATE_2019_PCT,
        EMPLOYMENT_RATE_PCT AS EMPLOYMENT_RATE_2019_PCT
    FROM CRI_DEV.MART.CMA_YEAR_LABOUR_MARKET
    WHERE REF_YEAR = 2019
)
SELECT
    MART.CMA_DGUID,
    MART.CMA_CODE,
    RTRIM(MART.CMA_NAME) AS CMA_NAME,
    MART.PROVINCE_NAME,
    MART.REF_YEAR,
    MART.REF_YEAR = LATEST_YEAR.REF_YEAR AS IS_LATEST_YEAR,
    MART.POPULATION,
    MART.POPULATION_YOY_PCT,
    ROUND(
        100 * MART.POPULATION / NULLIF(BASELINE.POPULATION_2019, 0),
        1
    ) AS POPULATION_INDEX_2019_EQ_100,
    ROUND(
        100 * (MART.POPULATION - BASELINE.POPULATION_2019)
        / NULLIF(BASELINE.POPULATION_2019, 0),
        2
    ) AS POPULATION_CHANGE_VS_2019_PCT,
    MART.UNEMPLOYMENT_RATE_PCT,
    ROUND(
        MART.UNEMPLOYMENT_RATE_PCT
        - BASELINE.UNEMPLOYMENT_RATE_2019_PCT,
        1
    ) AS UNEMPLOYMENT_RATE_CHANGE_VS_2019_PP,
    MART.PARTICIPATION_RATE_PCT,
    ROUND(
        MART.PARTICIPATION_RATE_PCT
        - BASELINE.PARTICIPATION_RATE_2019_PCT,
        1
    ) AS PARTICIPATION_RATE_CHANGE_VS_2019_PP,
    MART.EMPLOYMENT_RATE_PCT,
    ROUND(
        MART.EMPLOYMENT_RATE_PCT - BASELINE.EMPLOYMENT_RATE_2019_PCT,
        1
    ) AS EMPLOYMENT_RATE_CHANGE_VS_2019_PP
FROM CRI_DEV.MART.CMA_YEAR_LABOUR_MARKET AS MART
CROSS JOIN LATEST_YEAR
INNER JOIN BASELINE
    ON MART.CMA_DGUID = BASELINE.CMA_DGUID
ORDER BY MART.CMA_NAME, MART.REF_YEAR;
